FROM python:3.9.7

WORKDIR /app
# COPY . .
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
# RUN python -m nltk.downloader punkt
# RUN python -m nltk.downloader stopwords

# COPY ./flask-api/ .

ENV FLASK_APP=app.py

# ENV FLASK_ENV=development

CMD ["flask", "run", "--host", "0.0.0.0","--port","6000"]